plugins {
    id 'idea'
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    plugins.withId('idea') {
        idea.module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}

tasks.register('buildAll') {
    dependsOn ':forge-1.20.1:build'
}
