plugins {
    id 'com.gradleup.shadow'
}

def commonProject = project(':common-1.21.1')
ext.minecraft_version = commonProject.minecraft_version
ext.architectury_api_version = commonProject.architectury_api_version
ext.neoforge_version = commonProject.neoforge_version

architectury {
    platformSetupLoomIde()
    neoForge()
}

sourceSets.main.java.srcDir('../shared/loader-neoforge/src/main/java')
sourceSets.main.resources.srcDir('../shared/loader-neoforge/src/main/resources')

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    neoForge "net.neoforged:neoforge:$project.neoforge_version"

    modImplementation "com.nstut:openui-mc-neoforge-1.21.1:${rootProject.openui_version}"
    modImplementation "dev.architectury:architectury-neoforge:$project.architectury_api_version"

    implementation project(':common')

    common(project(path: ':common-1.21.1', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common-1.21.1', configuration: 'transformProductionNeoForge')
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'archives_name', rootProject.archives_name
    inputs.property 'mod_name', rootProject.mod_name
    inputs.property 'mod_description', rootProject.mod_description
    inputs.property 'mod_authors', rootProject.mod_authors
    inputs.property 'minecraft_version', project.minecraft_version
    inputs.property 'neoforge_version_range', '[21,)'
    inputs.property 'openui_version', rootProject.openui_version
    inputs.property 'mod_id', rootProject.mod_id

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version,
                archives_name: rootProject.archives_name,
                mod_name: rootProject.mod_name,
                mod_description: rootProject.mod_description,
                mod_authors: rootProject.mod_authors,
                minecraft_version: project.minecraft_version,
                neoforge_version_range: '[21,)',
                openui_version: rootProject.openui_version,
                mod_id: rootProject.mod_id
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
