modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/nstut/economy/issues"

[[mods]]
modId = "economy"
version = "${version}"
displayName = "NsTut Economy"
authors = "NsTut"
description = '''
A complete in-game economy for trading items and fluids. Use the Market Terminal to browse prices, create and manage orders, track your portfolio, send coins to other players, and connect your Vaults and Fluid Tanks to the market.
'''

[[dependencies.economy]]
modId = "openui_mc"
mandatory = true
versionRange = "[0.2,1)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.economy]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.economy]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
