modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId = "economy"
version = "${version}"
displayName = "Economy"
authors = "NsTut"
description = '''
A global economy system with currency, trading, and vault storage.
'''

[[dependencies.economy]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.economy]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
