plugins {
    id 'java-library'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'idea'
}

sourceSets.main.java.srcDir rootProject.file('common/src/main/java')
sourceSets.main.resources.srcDir rootProject.file('common/src/main/resources')

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${rootProject.archives_name}" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${rootProject.archives_name}" {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

def resourceTargets = ['META-INF/mods.toml']

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
        minecraft_version_range: project.minecraft_version_range,
        forge_version_range    : project.forge_version_range,
        loader_version_range   : project.loader_version_range,
        version                : rootProject.mod_version
    ]
    inputs.properties replaceProperties
    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title'     : rootProject.archives_name,
            'Specification-Vendor'    : rootProject.maven_group,
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : rootProject.maven_group
        ])
    }
    archiveBaseName = rootProject.archives_name
}
